### PR TITLE
Fastapi migration

### PR DESCRIPTION
**Pull request by dreulavelle**
Tested by requesting a movie/show on Overseerr and scraped/downloaded successfully.

One thing I noticed is web UI states aren't updating properly, but need help with this though.

- FastAPI migration complete. 
- Split controllers into separate modules.
- Correct name in Readme

### CODE REVIEW

**Comment by AyushSehrawat** [comment]
Remove `controller.py` since it's not required right now and will be implemented similarly to how `items.py` and `settings.py`

**Comment by dreulavelle** [comment]
I only left it because he had it there from before. Can totally delete the file though

**Comment by AyushSehrawat** [comment]
> I only left it because he had it there from before. Can totally delete the file though

Yeah will implement those in future 😄

**Review by Gaisberg — APPROVED** [review]
Fine by me.

**Review by AyushSehrawat — APPROVED** [review]

**Pull request merged**
