### PR TITLE
Compare default settings and current settings and populate missing keys

### PR DESCRIPTION
**Pull request by Gaisberg**

### CODE REVIEW

**Review by dreulavelle — CHANGES_REQUESTED** [review]
We should move to generating/validating the settings based on a schema. Pydantic is good for this.

**Comment by dreulavelle** [comment]
I can put this on my todo list if needed

**Comment by dreulavelle** [comment]
Whats the status of this?

**Comment by AyushSehrawat** [comment]
Closed as will be done with #204 by @omnunum

**Pull request closed without merging**
